apollo:
    # Turns on GraphQL Playground
    playground: true

    # Turns on GraphQL Introspection
    # If playground is enabled, but introspection is disabled,
    # the playground might not work properly as expected
    introspection: true
