FROM node:18

WORKDIR /app

# Install dependencies
COPY *.json ./yarn.lock ./
RUN yarn install

# Run Source Code
COPY ./src ./src
RUN yarn dev

# FROM node:18
# COPY . .
# WORKDIR /app
# COPY ./*.js ./package.json ./tsconfig.json ./yarn.lock ./default.yaml ./

USER 1000

CMD ["lib/servers/graphql-main.js"]
