version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: diameter
      POSTGRES_PASSWORD: span
      POSTGRES_DB: autifynetwork
    volumes:
      - db_data:/var/lib/postgresql/data
  prisma:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.dev
    command: npx prisma studio
    links:
      - db
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.dev
    command: >
        sh -c "npx prisma migrate deploy --name init && yarn dev"
volumes:
  db_data:
