apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: autifynetwork/app:tag 
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: postgres://username:password@db:5432/autifynetwork
