name: push-docker-image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Load secrets and save it in the environment
        run: aws secretsmanager get-secret-value --secret-id autback --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' >> .env
      - name: Create .env file and set build context
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
        env:
          DOCKER_BUILD_CONTEXT: . 
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: autifynetwork/app:${{ github.sha }}
          build-args: DATABASE_URL=${{ secrets.DATABASE_URL }}


