name: "Spinup Server"

on:
    push:
      branches:
        - 'main'

jobs:
  check-code:
    name: Spinup Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: sudo apt install direnv -y
    - run: yarn install
    - run: make deps
    - name: Run Server & Get Healthz
      run: |
        . ./.envrc && yarn start &
        set +e
        for i in {1..30}; do
          echo "Attempt ${i} to curl healthz"
          curl --fail http://localhost:80/healthz
          if [[ $? == 0 ]]; then success="true"; break; fi;
          sleep 1
        done
        set -e

        if [[ "$success" != "true" ]]; then echo "Server Spinup Test failed" && exit 1; fi;
